services:
  postgres-evolution:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis-evolution:
    image: redis:8
    restart: unless-stopped
    command:
      - redis-server
      - --loadmodule
      - /usr/local/lib/redis/modules/redisbloom.so
      - --loadmodule
      - /usr/local/lib/redis/modules/redisearch.so
      - --loadmodule
      - /usr/local/lib/redis/modules/redistimeseries.so
      - --loadmodule
      - /usr/local/lib/redis/modules/rejson.so

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  evolution-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
      - evolution/.env
    depends_on:
      - postgres-evolution
      - redis-evolution
      - rabbitmq

  nginx:
    image: nginx:1.23-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - evolution-api

volumes:
  pgdata:
  rabbitmqdata:
