# docker-compose.yaml
version: '3.8'

services:
  postgres-evolution:
    image: postgres:14
    container_name: postgres-evolution
    hostname: postgres-evolution
    restart: always
    volumes:
      - ./database/evolution/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=evolution
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=evolution
    networks:
      - evolution-network

  redis-chatwoot:
    image: redis:alpine
    container_name: redis-chatwoot
    hostname: redis-chatwoot
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file:
      - .env
    volumes:
      - ./database/chatwoot/redis:/data
    networks:
      - evolution-network

  redis-evolution:
    image: redis:alpine
    container_name: redis-evolution
    hostname: redis-evolution
    restart: always
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --port
      - "6379"
    env_file:
      - ./evolution-api/.env
    volumes:
      - ./database/evolution/redis:/data
    networks:
      - evolution-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./database/evolution/rabbitmq:/var/lib/rabbitmq
    networks:
      - evolution-network

  evolution:
    image: atendai/evolution-api:v2.2.1
    container_name: evolution-api
    volumes:
      - ./evolution-api/evolution_instances:/evolution/instances
    env_file:
      - ./evolution-api/.env
    networks:
      - evolution-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    entrypoint: nginx -g "daemon off;"
    ports:
      - 8080:8080   # Evolution API
      - 8081:8081   # Chatwoot
      - 8082:8082   # pgAdmin (if you add it)
    networks:
      - evolution-network
    depends_on:
      - evolution

networks:
  evolution-network:
    driver: bridge
    name: evolution-network
